name: Snyk SAST
on:
  workflow_dispatch:

jobs:
  Snyk-SAST-Scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
      - name: install snyk
        run: npm install -g snyk
      - name: Configure environment
        run: snyk config environment SNYK-GOV-01
      - name: Authenticate with Snyk SaaS
        run: snyk auth --org="${{ secrets.SNYK_ORG_ID }}" --client-id="${{ secrets.SNYK_CLIENT_ID }}" --client-secret="${{ secrets.SNYK_CLIENT_SECRET }}"
      - name: Run SAST
        run: snyk code test --org="${{ secrets.SNYK_ORG_ID }}" --sarif-file-output=snyk_sast.sarif
      - name: Upload SARIF file to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_sast.sarif
